// This file is auto-generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli && flutterfire configure
// to generate a real version of this file after setting up Firebase.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// You MUST replace these placeholder values with your real Firebase config.
/// Steps:
/// 1. Create a Firebase project at https://console.firebase.google.com
/// 2. Add an Android app with package name: com.nitara.pregnancyapp
/// 3. Download google-services.json → place in android/app/
/// 4. Run: flutterfire configure
/// 5. This file will be auto-generated with correct values
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web not supported for Nitara.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  // ⚠️ REPLACE THESE VALUES with your Firebase project config
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:android:YOUR_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'nitara-pregnancy-app',
    storageBucket: 'nitara-pregnancy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:ios:YOUR_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'nitara-pregnancy-app',
    storageBucket: 'nitara-pregnancy-app.appspot.com',
    iosBundleId: 'com.nitara.pregnancyapp',
  );
}
